### ISSUE TITLE
Homework Feedback JS2 Week 3

### ISSUE THREAD

**Issue by r0hitsharma** [aina21/hyf-homework#2]
Looks good, but if you couldn't get your game to run, then you're very welcome to ask for more help in the channel. Pay attention to some of the following:

https://github.com/aina21/hyf-homework/blob/eaf997e54f90c2f9608bee00d0333500ef6ec1c1/javascript/javascript2/week3/theFastestPresser%20/script/main.js#L51

It's better to keep the `return` type of the function consistent, will lead to fewer errors when you handle the results.

https://github.com/aina21/hyf-homework/blob/eaf997e54f90c2f9608bee00d0333500ef6ec1c1/javascript/javascript2/week3/theFastestPresser%20/script/main.js#L113

Better to use `setTimeout` here if you only want it to run once.

https://github.com/aina21/hyf-homework/blob/eaf997e54f90c2f9608bee00d0333500ef6ec1c1/javascript/javascript2/week3/theFastestPresser%20/script/main.js#L126

Use strict equality operator(`===`) for these comparisons, or in general as much as possible.

https://github.com/aina21/hyf-homework/blob/eaf997e54f90c2f9608bee00d0333500ef6ec1c1/javascript/javascript2/week3/functionAsAVariable.js#L34

Please don't name variables starting with a capital letter, just a matter of convention. It's kept for `static` methods and `class` names.

**Comment by aina21** [comment]
Hi Rohit

Thank you for feedback. I try to fix them :)
Actually in this line
https://github
.com/aina21/hyf-homework/blob/eaf997e54f90c2f9608bee00d0333500ef6ec1c1/javascript/javascript2/week3/theFastestPresser%20/script/main.js#L113
I used setInterval to show remaining time to the user, how can I use
setTimeout?

Thanks
Ida
