### ISSUE TITLE
Homework feedback Node.js week 2

### ISSUE THREAD

**Issue by r0hitsharma** [aina21/hyf-homework#8]
Works well. Slight issue with routing pointed out, which is a best practice, so I would like you to implement.

https://github.com/aina21/hyf-homework/blob/66b3532f95ff5133fb099c1735173182ed4662b9/nodejs/week2/mealSharingWebsite/package.json#L5

You can also change `main` parameter here to indicate your startup file and not have to repeat it in the commands to follow.

You should use `app.use` at this level so that the router can decide if it wants to accept `GET/PUT/POST` etc.

https://github.com/aina21/hyf-homework/blob/66b3532f95ff5133fb099c1735173182ed4662b9/nodejs/week2/mealSharingWebsite/src/backend/index.js#L18

This is unnecessary if you are already assigning the whole resource to the router.

https://github.com/aina21/hyf-homework/blob/66b3532f95ff5133fb099c1735173182ed4662b9/nodejs/week2/mealSharingWebsite/src/backend/routes/reservations.js#L6

If you would've done `app.use` in your main file, then you could just define relative urls here.

**Comment by aina21** [comment]
Thanks for feedback. I just fixed it :)
